### ISSUE TITLE
Manage role-capabilities

### ISSUE THREAD

**Issue by latour-gui** [LeGroupeDeFer/infom114_LaboMDL#77]
Front & Backend for managing roles & capabilities

## Milestones

- CRUD roles
- GET capabilities
- assign capability to role
- assign role to user

**Comment by latour-gui** [comment]
At the moment (branch issue_77, commit 5ae007e) it is possible to retrieve capabilities when a user is authenticated.

To be able to retrieve some valuable information with a GET to the API, you need to send as a header the `auth_token` given on the login and stored in the browser local_storage.
This header must be named `authorization` and the content must be formated like so : `Bearer <token>`

**Comment by latour-gui** [comment]
Now (e63cecc) it's also true for the GET /api/roles

@sady410  & @tsepton, you should now be able to get some values to interact with :D

**Comment by latour-gui** [comment]
So here's a list of what's left to do, I'll try to do it today :

- [ ] create route + controller for POST /api/user/role
- [ ] create route + controller for DELETE /api/user/role
- [ ] add role update tests
- [ ] add role delete tests
- [ ] add role assign tests

**Comment by latour-gui** [comment]
hey @sady410, for me everything that's backend-related is implemented, documented and tested.

That does not mean that it's perfect, but I think one may be able to link front & back.

**Comment by latour-gui** [comment]
unassining myself since I feel I cannot do more for this issue
